service: cvs-svc-app-logs

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: "20201221"
  region: ${env:AWS_PROVIDER_REGION, 'local'}

package:
  individually: true

functions:
  postLogs:
    handler: src/functions/postLogs/framework/handler.handler
    events:
      - http:
          path: "logs"
          method: post

custom:
  webpack:
    webpackConfig: "webpack-sls-offline.config.js"

plugins:
  - serverless-webpack
  - serverless-offline
