service: cvs-svc-app-logs

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: "20201221"
  region: ${env:AWS_PROVIDER_REGION, 'local'}

package:
  individually: true

functions:
  postLogs:
    handler: build/handler.handler
    events:
      - http:
          path: "logs"
          method: post

plugins:
  - serverless-offline
