name: 👀 Collect Stale Environments

run-name: 👀 Collect Stale Environments 👾 ${{ github.actor }}

on:
  push:
    branches:
        - feature/CB2-11814
#   workflow_dispatch:
#     inputs:
#       dry_run:
#         description: Dont perform, just output information
#         type: boolean
#         default: false

permissions:
  id-token: write
  contents: write

jobs:
  collect-stale-branches:
    name: Collect Stale branches
    env:
     GH_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: X64
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: List all branches 
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/dvsa/cvs-svc-app-logs/branches --jq '.[].name | select(test("feature/*"))'