name: 👀 Collect Stale Environments

run-name: 👀 Collect Stale Environments 👾 ${{ github.actor }}

on:
  push:
    branches:
      - feature/CB2-11814

permissions:
  id-token: write
  contents: write

jobs:
  collect-stale-branches:
    name: Collect Stale branches
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: X64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List all branches with pagination
        run: |
          page=1
          per_page=100
          branches=()

          while true; do
            response=$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/dvsa/cvs-svc-app-logs/branches?per_page=$per_page\&page=$page \
              --jq '.[].name | select(test("^(main|master|release|develop|devops|HEAD)$") | not)')
            
            if [[ -z "$response" ]]; then
              break  # Exit loop if no more results
            fi

            branches+=($response)
            ((page++))
          done

          # Output all branches for debugging
          echo "Fetched branches: ${branches[@]}"

      - name: Get commit dates older than 3 months for each branch
        run: |
            echo "Checking commits for branch: $branch"

            # Fetch the full commit history for the branch to check dates
            commit_dates=$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/dvsa/cvs-svc-app-logs/commits?sha=$branch \
              --jq '.[].commit.committer.date' 2>/dev/null)
