name: 👀 Collect Stale Environments

run-name: 👀 Collect Stale Environments 👾 ${{ github.actor }}

on:
  push:
    branches:
      - feature/CB2-11814

permissions:
  id-token: write
  contents: write

jobs:
  collect-stale-branches:
    name: Collect Stale branches
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: X64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List all branches with pagination
        id: branches
        run: |
          page=1
          per_page=100
          branches=()

          while true; do
            response=$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/dvsa/cvs-svc-app-logs/branches?per_page=$per_page\&page=$page \
              --jq '.[].name | select(test("^(main|master|release|develop|devops|HEAD)$") | not)')
            
            if [[ -z "$response" ]]; then
              break  # Exit loop if no more results
            fi

            branches+=($response)
            ((page++))
          done

          # Output all branches for debugging
          echo "Fetched branches: ${branches[@]}"

      - name: Get commit dates older than stale branch threshold
        run: |
          # Use the environment variable for grace period, default to 3 months if not set
          stale_threshold=${{ env.stale-branch-threshold || '3m' }}

          # Get the date that is 'stale_threshold' ago
          three_months_ago=$(date -u -v-"$stale_threshold" +%s)

          for branch in $(jq -r '.[]' <<< '${{ steps.branches.outputs.branches }}'); do
              # Fetch commit dates for the branch
              commit_dates=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/dvsa/cvs-svc-app-logs/commits?sha=$branch \
                  --jq '.[].commit.committer.date' 2>/dev/null)

              while IFS= read -r commit_date; do
                  # Convert commit date to seconds since epoch
                  commit_date_seconds=$(date -j -f "%Y-%m-%dT%H:%M:%SZ" "$commit_date" +%s)

                  if [[ $commit_date_seconds -lt $three_months_ago ]]; then
                      echo "Branch $branch has commits older than $stale_threshold: $commit_date"
                  fi
              done <<< "$commit_dates"
          done
        env:
          stale-branch-threshold: "3m" 
